### ISSUE TITLE
好厉害啊

### ISSUE THREAD

**Issue by CHEBSR** [uniquebai/javaweb_demo#1]
这啥啊 什么项目啊 holy害 见都没见过 我都跑不通 太高级了

**Comment by cc19980718** [comment]
``

**Comment by uniquebai** [comment]
谢谢你的谬赞，我真的太感动了，我的项目刚刚发出去，就有人发疯，i really fucking happy



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "uniquebai/javaweb_demo"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月22日(星期五) 晚上9:03
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[uniquebai/javaweb_demo] 好厉害啊 (Issue #1)





 
这啥啊 什么项目啊 holy害 见都没见过 我都跑不通 太高级了
